/**
 * Example of creating a new user and logging on console with inserted id
 * auto-generated by MongoDB
 * @param client MongoDB client
 */
const createUser = async (client, newUser) => {
  const result = await client
    .db("my_database")
    .collection("users")
    .insertOne(newUser);

  console.log(`examples/create-user.js - New user created with the following id: ${result.insertedId}`);
  console.log('');
}

module.exports = { createUser }